CREATE TABLE `coin_info` (

`id` INT(10) NOT NULL AUTO_INCREMENT ,
`urlPTitle` VARCHAR(255) NOT NULL ,

`title` VARCHAR(255) NOT NULL ,
`imageUrl` VARCHAR(255) NOT NULL ,
`created` DATETIME,

`erUSD` VARCHAR(20) NOT NULL ,
`erBTC` VARCHAR(20) NOT NULL ,
`erRUR` VARCHAR(20) NOT NULL ,
`erEUR` VARCHAR(20) NOT NULL ,

`cUSD` VARCHAR(20) NOT NULL ,
`oUSD` VARCHAR(20) NOT NULL ,
`v` VARCHAR(40) NOT NULL ,
`e` VARCHAR(40) NOT NULL ,


PRIMARY KEY (`id`),
UNIQUE (`urlPTitle`)

) ENGINE = InnoDB;
ALTER TABLE `coin_info` CHANGE `created` `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP;
