CREATE TABLE `exchange_pairs` (

`id` INT(10) NOT NULL AUTO_INCREMENT ,
`urlPTitle` VARCHAR(255) NOT NULL ,
`imageUrl` VARCHAR(255) NOT NULL ,

`u` VARCHAR(255) NOT NULL ,
`ct` VARCHAR(40) NOT NULL ,
`pt` VARCHAR(20) NOT NULL ,
`s` VARCHAR(20) NOT NULL ,
`p` VARCHAR(20) NOT NULL ,
`o` VARCHAR(20) NOT NULL ,
`d` VARCHAR(3) NOT NULL ,
`t` VARCHAR(30) NOT NULL ,

PRIMARY KEY (`id`)

) ENGINE = InnoDB;
